# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 18:19
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(choices=[('theory_type', 'Theory type'), ('lab_type', 'Lab type')], max_length=15)),
                ('course_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('max_marks', models.PositiveSmallIntegerField(default=0)),
                ('marks', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(models.PositiveSmallIntegerField(default=0), message='No Apsara dark logic please -_-')])),
                ('comment', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.Course')),
            ],
        ),
    ]
