# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 22:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('performance', '0003_auto_20171009_0308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='name',
            new_name='exam_name',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='marks',
            new_name='marks_obt',
        ),
        migrations.RemoveField(
            model_name='course',
            name='user',
        ),
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
