# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0005_auto_20171009_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('theory', 'Theory'), ('lab', 'Lab')], max_length=15),
        ),
    ]
