# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 05:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0007_auto_20171009_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('theory', 'Theory'), ('lab', 'Lab')], max_length=10),
        ),
        migrations.AlterField(
            model_name='exam',
            name='marks_obt',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100, message='No Apsara dark logic please -_-')]),
        ),
    ]
