# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0009_auto_20171009_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='name',
        ),
    ]
