# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0010_auto_20171020_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='exam_name',
            new_name='name',
        ),
    ]
