# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0012_auto_20171020_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_credits',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_type',
        ),
        migrations.RemoveField(
            model_name='course',
            name='grade_obt',
        ),
        migrations.AddField(
            model_name='exam',
            name='weightage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
