# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0013_auto_20171020_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.AddField(
            model_name='course',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
