# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0002_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('description', models.TextField()),
            ],
        ),
    ]
