# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0004_auto_20171009_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('I prefer not to say', 'I prefer not to say')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='univ',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
