# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_customgroup_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='is_requested',
            field=models.BooleanField(default=False),
        ),
    ]
